### ISSUE TITLE
通过网络获取数据的示例报错

### ISSUE THREAD

**Issue by fujiawei-dev** [BrinedFish0222/flutter_kline#4]
分时图运行是正常的，但K线部分报错：

> [log] 更新日K数据，数据长度：1
> [log] KChartDataSource notifyListeners rightmost
> ======== Exception caught by rendering library =====================================================
> The following assertion was thrown during paint():
> Rect argument contained a NaN value.
> 'dart:ui/painting.dart':
> Failed assertion: line 26 pos 10: '<optimized out>'
> 
> The relevant error-causing widget was: 
>   KChartWidget KChartWidget:file:///D:/AppGallery/GitHub/flutter_kline/example_network/lib/example_network/example_day_network_widget.dart:78:12
> When the exception was thrown, this was the stack: 
> #2      _rectIsValid (dart:ui/painting.dart:26:10)
> #3      _NativeCanvas.drawRect (dart:ui/painting.dart:5936:12)
> #4      CandlestickPainter.paint (package:flutter_kline/painter/candlestick_painter.dart:30:12)
> #5      CandlestickChartPainter.paint (package:flutter_kline/painter/candlestick_chart_painter.dart:56:9)
> #6      CandlestickChart.paint (package:flutter_kline/chart/candlestick_chart.dart:37:7)
> #7      ChartRenderer.paint (package:flutter_kline/renderer/chart_renderer.dart:80:12)
> #8      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:588:13)
> #9      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:630:7)

**Comment by BrinedFish0222** [comment]
很抱歉，很长一段时间估计都不会再维护网络示例，实在是不够精力，后续有时间精力也是慢慢迭代K线图的画线功能。
